language: node_js
node_js:
  - "4.0"
addons:
  firefox: "51.0.1"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.14.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
cache:
  directories:
    - ".meteor"
    - ".babel-cache"
script: TEST_PACKAGES_EXCLUDE="less" ./packages/test-in-console/run.sh
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
