language: node_js
node_js:
  - "4.0"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - git clone https://github.com/scheib/chromium-latest-linux.git chrome
  - cd chrome/ && sh update.sh
  - pwd
  - ls -la
  - ls -la chrome/
  - ls -la chrome/latest/
  - export PATH=$PATH:$PWD/chrome/latest
  - wget https://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - mkdir chromedriver
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
cache:
  directories:
    - ".meteor"
    - ".babel-cache"
script: TEST_PACKAGES_EXCLUDE="less" ./packages/test-in-console/run.sh
sudo: false
env:
  - CXX=g++-4.8
